apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: construo-us-tls
spec:
  secretName: construo-us
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: construo.us
  dnsNames:
    - construo.us
    - fib-calculator.construo.us
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - construo.us
          - fib-calculator.construo.us